# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'travis-ci-integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'

  # Pods for travis-ci-integration

  target 'travis-ci-integrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'travis-ci-integrationUITests' do
    # Pods for testing
  end

end
